### ISSUE TITLE
New Relic node module ETIMEDOUT

### ISSUE THREAD

**Issue by guilhermesteves** [TooTallNate/gnode#20]
Do you know any new relic related bug?

Every time I use Newrlic's module, I get a timeout.

```javascript
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ETIMEDOUT
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)
```

If I find anything related I'l report here. :)

Also, great job with gnode.

**Comment by TooTallNate** [comment]
I'd need to see some code first.

**Comment by guilhermesteves** [comment]
Well, I'm sorry but the problem probably isn't happening in gnode, a in an express app, the simple require('newrelic') was causing a timeout in an wrapper.

As far as I know, inside the newrelic/lib/instrumentation/core/net.js and this function is probably breaking everything.

I'm going to open an issue in [node-newrelic](https://github.com/newrelic/node-newrelic)

Thanks for the answer.
