### ISSUE TITLE
only use regenerator when necessary

### ISSUE THREAD

**Issue by jonathanong** [TooTallNate/gnode#5]
right now, my app takes forever to start up with gnode. looking at the code, it seems like you run _every_ module through regenerator.

is there a way to do something like:

``` js
try {
  var module = require('./something')
} catch (err) {
  var module = requireWithRegenerator('./something')
}
```

? even a `~body.indexOf('*')` would see an improvement.

this is of course assuming i'm reading the source correctly. not too sure what's going on since i'm not familiar with node's internals.

**Comment by raine** [comment]
I'm using gnode with a cli tool through the programmatic API i.e. `require('gnode'); doStuff()`.

`node --harmony index.js` starts a lot faster than `node index.js`, so the programmatic API doesn't seem to check for availability of generators in `node`, perhaps on purpose?
